/**
 * The examples gallery each framework track renders
 * (src/tracks/examples.mdx), one card per shipped example that belongs to
 * that track. Every card's screenshot is generated by the committed
 * Playwright script, e2e/scripts/generate-example-screenshots.mjs, checked
 * into apps/docs/public/examples; re-run it whenever an example's visuals
 * change.
 *
 * Every example shows on the one track it actually belongs to, by what it
 * depends on, never by which guide happens to mention it: react-movie-stack,
 * react-recipes, react-infinite-feed, nextjs-app-router and vertical-stack
 * (a plain `@rpxl/riffle/react` app, `axis: 'y'`) are React's; vue-movie-stack,
 * vue-recipes, vue-clamp-controls and nuxt-example are Vue's;
 * vanilla-movie-stack, vanilla-basic, vanilla-recipes and custom-layout (a
 * plain `@rpxl/riffle` core app, no framework adapter at all) are vanilla's. Vanilla's and Vue's own vertical
 * axis recipes live inside their own recipes apps instead of as a
 * standalone example (see vanilla-recipes' `vertical.ts` and vue-recipes'
 * `VerticalStack.vue`), so there is no vanilla or Vue `vertical-stack` card
 * to show here.
 */
import type { Framework } from './track-snippets'

export interface ExampleCard {
  /** The example's directory name under examples/, and its screenshot's basename. */
  name: string
  title: string
  description: string
  /** public/examples/<name>.webp, generated by generate-example-screenshots.mjs. */
  screenshot: string
  /** What the screenshot itself shows, not the card's own description. */
  alt: string
  /** The example's own directory, relative to the repository root. */
  source: string
}

const vanillaBasic: ExampleCard = {
  name: 'vanilla-basic',
  title: 'vanilla-basic',
  description:
    'A single HTML file: no build step, no framework, @rpxl/riffle loaded from a CDN ' +
    '<script type="module"> import.',
  screenshot: '/riffle/examples/vanilla-basic.webp',
  alt: 'A preview of the vanilla-basic example: five color cards fanned behind a blue front card labelled 1, with Prev and Next buttons below.',
  source: 'examples/vanilla-basic',
}

const vanillaMovieStack: ExampleCard = {
  name: 'vanilla-movie-stack',
  title: 'vanilla-movie-stack',
  description:
    'The hero with no framework: a fanned poster stack built by hand on createRiffle(), ' +
    'with Previous/Next buttons.',
  screenshot: '/riffle/examples/vanilla-movie-stack.webp',
  alt: 'A preview of the vanilla-movie-stack example: a fanned stack of movie posters with Neon Harbor, 1998 on the front card.',
  source: 'examples/vanilla-movie-stack',
}

const vanillaRecipes: ExampleCard = {
  name: 'vanilla-recipes',
  title: 'vanilla-recipes',
  description:
    'The four recipe pages, mounted with plain createRiffle() and no build-tool adapter: ' +
    'infinite feed, clamp with controls, programmatic control, forms inside cards, plus a ' +
    'vertical stack.',
  screenshot: '/riffle/examples/vanilla-recipes.webp',
  alt: 'A preview of the vanilla-recipes example: a stack of film cards, each with a title, a label and a text input, with Prev and Next buttons below.',
  source: 'examples/vanilla-recipes',
}

const reactMovieStack: ExampleCard = {
  name: 'react-movie-stack',
  title: 'react-movie-stack',
  description:
    'The hero: a fanned stack of movie posters, recreating the original mockup. <Riffle> ' +
    'drop-in, a riffleRef driving external Previous/Next buttons, getLabel for a real ' +
    'accessible name per card.',
  screenshot: '/riffle/examples/react-movie-stack.webp',
  alt: 'A preview of the react-movie-stack example: a fanned stack of movie posters with Neon Harbor, 1998 on the front card.',
  source: 'examples/react-movie-stack',
}

const reactRecipes: ExampleCard = {
  name: 'react-recipes',
  title: 'react-recipes',
  description:
    'The recipe pages built with the React adapter: clamp with controls, programmatic ' +
    'control, forms inside cards, and a hand-written LayoutStrategy.',
  screenshot: '/riffle/examples/react-recipes.webp',
  alt: 'A preview of the react-recipes example: a stack of film cards, each with a title, a label and a text input, with Prev and Next buttons below.',
  source: 'examples/react-recipes',
}

const reactInfiniteFeed: ExampleCard = {
  name: 'react-infinite-feed',
  title: 'react-infinite-feed',
  description:
    'count growing under a live stack: an effect watches how close the active card is to the ' +
    'end and appends another page before you reach it.',
  screenshot: '/riffle/examples/react-infinite-feed.webp',
  alt: 'A preview of the react-infinite-feed example: numbered gradient cards in a stack, with Previous and Next controls and a Card 1 of 8 readout.',
  source: 'examples/react-infinite-feed',
}

const nextjsAppRouter: ExampleCard = {
  name: 'nextjs-app-router',
  title: 'nextjs-app-router',
  description:
    "Server-side rendering in Next.js's App Router: the stack mounts correctly with no " +
    'window access at import time, on both a dynamic route and a fully static one.',
  screenshot: '/riffle/examples/nextjs-app-router.webp',
  alt: 'A preview of the nextjs-app-router example: the same movie poster stack as react-movie-stack, server rendered.',
  source: 'examples/nextjs-app-router',
}

const vueMovieStack: ExampleCard = {
  name: 'vue-movie-stack',
  title: 'vue-movie-stack',
  description:
    'The hero: a fanned stack of movie posters on the useRiffle directives, with external ' +
    'Previous/Next buttons and getLabel for a real accessible name per card.',
  screenshot: '/riffle/examples/vue-movie-stack.webp',
  alt: 'A preview of the vue-movie-stack example: the same fanned stack of movie posters, with Neon Harbor, 1998 on the front card.',
  source: 'examples/vue-movie-stack',
}

const vueRecipes: ExampleCard = {
  name: 'vue-recipes',
  title: 'vue-recipes',
  description:
    'The recipe pages built with the Vue adapter: a vertical axis, infinite feed, ' +
    'programmatic control, forms inside cards, and a hand-written LayoutStrategy.',
  screenshot: '/riffle/examples/vue-recipes.webp',
  alt: 'A preview of the vue-recipes example: numbered gradient cards in a stack, with Previous and Next controls and a Card 1 of 8 readout.',
  source: 'examples/vue-recipes',
}

const vueClampControls: ExampleCard = {
  name: 'vue-clamp-controls',
  title: 'vue-clamp-controls',
  description:
    "bounds: 'clamp' instead of the default loop: the stack stops dead at both ends, and its " +
    'Previous/Next buttons go genuinely disabled there.',
  screenshot: '/riffle/examples/vue-clamp-controls.webp',
  alt: 'A preview of the vue-clamp-controls example: a stack of trail waypoint cards labelled with names and elevations, a Cedar Gate card in front, and a Card 1 of 5 readout.',
  source: 'examples/vue-clamp-controls',
}

const nuxtExample: ExampleCard = {
  name: 'nuxt-example',
  title: 'nuxt-example',
  description:
    "The same SSR proof, in the other ecosystem: Nuxt's Nitro server renders the stack with " +
    'no window access at import time either.',
  screenshot: '/riffle/examples/nuxt-example.webp',
  alt: 'A preview of the nuxt-example example: the same movie poster stack, server rendered through Nuxt.',
  source: 'examples/nuxt-example',
}

const customLayout: ExampleCard = {
  name: 'custom-layout',
  title: 'custom-layout',
  description:
    'Writing a LayoutStrategy from scratch: a spread() function replacing the default fan, ' +
    'shown live and explained on Layouts.',
  screenshot: '/riffle/examples/custom-layout.webp',
  alt: 'A preview of the custom-layout example: a blue front card labelled One with four more cards fanned out further to the right than the default layout, plus a 1 of 7 readout.',
  source: 'examples/custom-layout',
}

const verticalStack: ExampleCard = {
  name: 'vertical-stack',
  title: 'vertical-stack',
  description:
    "axis: 'y' instead of the default horizontal drag: cards fan downward, and the keyboard " +
    'maps to Up/Down instead of Left/Right.',
  screenshot: '/riffle/examples/vertical-stack.webp',
  alt: 'A preview of the vertical-stack example: a front card labelled Low Tide Radio with three more cards fanned downward beneath it, arrow-key hint text, and up and down controls.',
  source: 'examples/vertical-stack',
}

export const EXAMPLES: Record<Framework, ExampleCard[]> = {
  vanilla: [vanillaMovieStack, vanillaBasic, vanillaRecipes, customLayout],
  react: [reactMovieStack, reactRecipes, reactInfiniteFeed, nextjsAppRouter, verticalStack],
  vue: [vueMovieStack, vueRecipes, vueClampControls, nuxtExample],
}
